### ISSUE TITLE
No Config.DefaultSpawn but call for it on line 67 of client/main.lua

### ISSUE THREAD

**Issue by R3site** [Qbox-project/qbx-multicharacter#13]
**Describe the bug**
On line 67 of client/main.lua the code sets the entity coords of the player to Config.DefaultSpawn. The issue is that Config.DefaultSpawn does not exist. I would make a pull request, however I do not know if you guys would like to add a Default Spawn or do something else with it.  

**To Reproduce**
1. Create a new charachter
2. Attempt to spawn in.

**Expected behavior**
Spawn in somewhere, and then open the clothing menu.

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Today
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Additional context**
I made a solution to the problem simply by making Config.DefaultSpawn = vector3(-1035.71, -2731.87, 12.86); which is the airport. Like i said though I didnt know if you guys wanted to do something else with it.

**Comment by ChatDisabled** [comment]
Sorry, don't have a system setup yet to automatically view all the issues on the project. Either way https://github.com/Qbox-project/qbx-multicharacter/pull/14
