### ISSUE TITLE
for Berkie my love

### ISSUE THREAD

**Issue by TonybynMp4** [Qbox-project/qbx-multicharacter#19]
### The problem

This script stinks a lot (seems like a recurrent theme)

### Ideal solution

Remake the entire thing

### Alternative solutions

Cleanup the code, re-make the UI (rn it's using the built file of the Qsus (not qbus the other one) framework multichar so it's not editable + it def shouldn't need to be anything other than plain js since it's the most simple script there is UI wise

**Comment by TonybynMp4** [comment]
i'm pretty sure there's things to do but i can't think of any rn so if anyone thinks of stuff to add/remove/change go on this the right place

**Comment by Manason** [comment]
This resource is unsupported
